apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-mysql
  namespace: {{ .Values.mysql.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name: mysql
    port: {{ .Values.mysql.port }}
  clusterIP: None