apiVersion: v1
kind: Service
metadata:
  name: {{ include "todoapp.fullname" . }}
  namespace: {{ .Values.todoapp.namespace | default .Release.Namespace }}
spec:
  type: {{ .Values.todoapp.service.type | default "ClusterIP" }}
  ports:
    {{- range .Values.todoapp.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if eq $.Values.todoapp.service.type "NodePort" }}
      nodePort: {{ .nodePort }}
      {{- end }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
  selector:
    app: {{ include "todoapp.name" . }}