apiVersion: v1
kind: Service
metadata:
  name: todoapp-nodeport
  namespace: {{ .Values.todoapp.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.todoapp.namespace }}
  ports:
    {{- range .Values.spec.ports }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
      {{- if .nodePort }}  # Проверяем, задан ли nodePort
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
