name: python-deployment

run-name: ${{ github.actor }} - ${{ github.ref_name}} -${{ github.sha }}

on:
  push:
    branches: ["main", "test/develop"]
  pull_request:
    branches: ["main", "test/develop"]

env:
  PythonVersion: 3.8
  DockerImageName: ${{ secrets.DOCKERHUB_USERNAME }}/todoapp

jobs:
  python-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PythonVersion }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PythonVersion }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage flake8
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

      - name: Generate Report
        run: |
          coverage run --source='.' manage.py test
          coverage report

      - name: Linting
        run: |
          flake8 . --show-source --statistics --exit-zero

      - name: Check Complexity
        run: |
          flake8 . --exit-zero --max-complexity=6

      - name: Upload python artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-artifacts
          path: .

      - name: Upload helm artifacts
        if: github.ref_name == 'main' || github.ref_name == 'test/develop'
        uses: actions/upload-artifact@v4
        with:
          name: helm-artifacts
          path: ${{ github.workspace }}/helm-charts

  docker-ci:
    name: Build and Push Image
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' || github.ref_name == 'test/develop'
    needs: python-ci
    steps:

      - uses: actions/download-artifact@v4
        name: Download python artifacts
        with:
          name: python-artifacts
          path: .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./src
          tags: ${{ env.DockerImageName }}:${{ github.sha }}

  helm-ci:
    runs-on: ubuntu-latest
    needs: python-ci
    if: github.ref_name == 'main' || github.ref_name == 'test/develop'
    name: Helm CI Job
    steps:

    - uses: actions/download-artifact@v4
      name: Download helm artifacts
      with:
        name: helm-artifacts
        path: .

    - name: Set Up Helm
      uses: azure/setup-helm@v4.3.0

    - name: Lint helm
      run: helm lint ./todoapp

    - name: Template Helm
      run: |
          helm template todoapp \
          ./todoapp \
          -f ./todoapp/values.yaml

    - name: Package Helm
      run: helm package ./todoapp

    - name: Upload Helm Artifact
      uses: actions/upload-artifact@v4
      with:
        name: helm-package_on_helm-ci
        path: ./*.tgz

    - name: List files (debug)
      run: ls -la *.tgz

  deploy-helm-dev:
    if: github.ref_name == 'main' || github.ref_name == 'test/develop'
    needs: [docker-ci, helm-ci]
    name: Deploy helm
    uses: ./.github/workflows/deployment-workflow.yml
    secrets: inherit
    with:
      environment: develop
      helm-release-name: todoapp
      version: ${{ github.sha }}


  deploy-helm-staging:
    if: github.ref_name == 'main' || github.ref_name == 'test/develop'
    needs: deploy-helm-dev
    name: Deploy helm-staging
    uses: ./.github/workflows/deployment-workflow.yml
    secrets: inherit
    with:
      environment: staging
      version: ${{ github.sha }}
      helm-values-path: ./todoapp/values/stg.yaml
      helm-release-name: todoapp-staging
